version: '3.7'

services:
  portal:
    build:
      context: .
      cache_from:
        - swedbankpay/jekyll-plantuml:1.1.1
      dockerfile: .docker/Dockerfile
    container_name: developer_portal
    ports:
      - 4000:4000
      - 35729:35729
    volumes:
      - .:/srv/jekyll
      - .bundle:/usr/local/bundle
