name: Docker build site and publish

on: 
  push:
    branches: [ master ]
    tags: [ '*' ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Docker build site and publish
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker compose up
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_ACTOR: payex-dev
        GITHUB_ACTOR_EMAIL: dev@payex.com
        GITHUB_REPO: ${{ github.repository }}
      run: |
        docker-compose \
          -f docker-compose.yml \
          -f .docker/docker-compose.deploy.yml \
          up \
          --build \
          --abort-on-container-exit \
          --exit-code-from portal
